"""
Plots: VaR exception overlays and rolling exception counts.

Usage:
python plots.py --indir data/interim --pred outputs/forecasts/pred_ar1.parquet --risk_dir outputs/risk --outdir outputs/figures --alpha 0.01 --horizon 1 --window 250
"""
import argparse
from pathlib import Path

import matplotlib
import pandas as pd

from utils import LOGGER, ensure_dir, read_prediction_table

matplotlib.use("Agg")
import matplotlib.pyplot as plt


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--indir", type=str, default="data/interim")
    ap.add_argument("--pred", type=str, required=True)
    ap.add_argument("--risk_dir", type=str, required=True)
    ap.add_argument("--outdir", type=str, default="outputs/figures")
    ap.add_argument("--alpha", type=float, default=0.01)
    ap.add_argument("--horizon", type=int, default=1)
    ap.add_argument("--window", type=int, default=250)
    args = ap.parse_args()

    ensure_dir(args.outdir)

    # Validate/resolve the prediction input for consistent UX, even though
    # plotting itself only consumes var_backtest.csv generated by risk.py.
    _, pred_path = read_prediction_table(args.pred)
    LOGGER.info(f"Using prediction file: {pred_path}")

    bt_path = Path(args.risk_dir) / "var_backtest.csv"
    bt = pd.read_csv(bt_path, parse_dates=["date"])
    if bt.empty:
        raise RuntimeError("var_backtest.csv is empty. Run risk.py successfully before plots.py.")

    for series, group in bt.groupby("series"):
        fig, ax = plt.subplots(figsize=(8, 3))
        ax.plot(group["date"], group["y"], label="Realized")
        ax.plot(group["date"], group["VaR"], label=f"VaR {int(100 * args.alpha)}%")
        ax.fill_between(
            group["date"],
            group["VaR"],
            group["y"],
            where=group["y"] < group["VaR"],
            color="red",
            alpha=0.3,
            label="Exceptions",
        )
        ax.set_title(f"{series} - VaR Backtest (h={args.horizon})")
        ax.legend()
        fig.tight_layout()
        fig.savefig(Path(args.outdir) / f"var_backtest_{series}.png", dpi=160)
        plt.close(fig)

        exc = group.set_index("date")["exceed"]
        roll = exc.rolling(args.window).sum()
        fig, ax = plt.subplots(figsize=(8, 3))
        ax.plot(roll.index, roll.values)
        ax.axhline(4, linestyle="--")
        ax.axhline(9, linestyle="--")
        ax.set_title(f"{series} - Rolling {args.window}d exceptions")
        fig.tight_layout()
        fig.savefig(Path(args.outdir) / f"exceptions_rolling_{series}.png", dpi=160)
        plt.close(fig)

    LOGGER.info(f"Saved figures to {args.outdir}")


if __name__ == "__main__":
    main()
